### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by williamdes** [paultag/libolla#7]
Hi,

I just found your package on my QA dashboard: https://debian.dashboard.air-balloon.cloud/en/dashboard-ftp-rm-candidates

https://tracker.debian.org/pkg/olla

Be sure to upload a newer version to keep your package up to date

**Comment by paultag** [comment]
@williamdes I'll file a removal bug - thanks

**Comment by williamdes** [comment]
I can file a removal if you want, I am doing a bunch of them
You can find the script on my repository: https://github.com/air-balloon/debian-dashboard#qa-report

Let me know if you really want to do the RM

**Comment by paultag** [comment]
@williamdes I'm on the ftp-team (https://ftp-master.debian.org/). The bug is filed in 1028906, and I'll dak rm it myself. Thanks anyway :)

(I hope I can manage this without a script?)

**Comment by paultag** [comment]
```
Will remove the following packages from experimental:

      olla |        1.1 | source, amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x

Maintainer: Paul Tagliamonte <paultag@debian.org>
Will also close bugs: 1028906
Will also close associated bug reports.

------------------- Reason -------------------
ROM; not updated in a while, no longer a good idea
----------------------------------------------

Checking reverse dependencies...
No dependency problem found.

Going to remove the packages now.
Continue (y/N)? y
Deleting... done.
```

done, thanks for the report
